INSERT INTO Usuario VALUES ('joaovperin', 'joaovperin@live.com', '1234', 'João Victor', 'A');
INSERT INTO Usuario VALUES ('admin', 'admin@dallahits.com', 'admin', 'Administrador', 'A');
INSERT INTO Usuario VALUES ('fulano', 'fulanodetal@email.com', 'senha', 'Fulano de tal', 'R');
INSERT INTO Usuario VALUES ('narnia', '', '2', 'Nárnia', 'A');
INSERT INTO Usuario VALUES ('viccenzo', '', '1234', 'Jesus', 'A');

INSERT INTO Mensagem (Usuario, Msg) VALUES ('joaovperin', 'batata');
INSERT INTO Mensagem (Usuario, Msg) VALUES ('admin', 'Bom dia, usuários');

INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('Batata', '12.50');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('Vodka', '5.50');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('Whisky', '11.00');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('Água', '2.50');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('Refri lata', '3.50');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('FAR. AMIZADE A71	FARINHAS	', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('RLC 250 GR	EMBALAGENS - BOBINAS	', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('BERCO COQUETEL INTEGRAL LIGHT	BERCO DE PLASTICO	', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('COQUETEL INTEGRAL LIGHT 250 G	EMBALAGENS PLASTICAS - SACARIA	', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('PPLC- PASTEIS CALABRESA 280 GR	EMBALAGENS - CAIXAS PAPELAO	', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('ERVA MATE TRADICIONAL 1KG		', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('ERVA MATE TRADICIONAL 500G		', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('MASSA ESPAGUETE ESPINAFRE 500G		', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('PASTEL DE FORNO MEDIO 300G.		', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('FRESA TOPO RET 2C MD K40 TINAL		', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('MASSA FOLHADA ROLO 300G', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('PASTEL PRONTO DE CARNE 280G		', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('PASTEL PRONTO DE CARNE 1000G		', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('PASTEL PRONTO DE QUEIJO 280G		', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('PASTEL PRONTO DE QUEIJO 1000G		', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('MASSA COLORIDA		', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('RETALHO RAVIOLI 500g		', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('RAVIOLI DE CARNE 250G		', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('RAVIOLI QUATRO QUEIJOS 1000G		', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('MARC.PROPRIA RCR47		', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('MARC.PROPRIA RFR51		', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('RAVIOLI QUATRO QUEIJOS 250G		', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('RAVIOLI DE FRANGO 1000G		', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('RAVIOLI DE FRANGO ROMANHA 2KG		', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('RAVIOLI DE CARNE ROMANHA 2KG		', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('EXTRATO DE TOMATE 270GR		', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('RETALHO DE CAPELETTI 500G		', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('RETALHO CAPELETTI LEGUMES 500G		', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('CAPELLETI DE CARNE		', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('SORVETE NAPOLITANO		', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('CAP. 5 QUEIJOS DE KILO		', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('MARC.PROPRIA CCR46', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('MARC.PROPRIA CFR50', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('CAPELETTI DE LEGUMES 250G		', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('CAPELETTI DE FRANGO 1000G		', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('CAPELLETI DE CARNE ROMANHA', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('PASTEL PRONTO DE CARNE 280G', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('PASTEL PRONTO DE CARNE 1000G', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('PASTEL PRONTO DE QUEIJO 280G', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('PASTEL PRONTO DE QUEIJO 1000G', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('MASSA COLORIDA', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('RETALHO RAVIOLI 500g', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('RAVIOLI DE CARNE 250G', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('RAVIOLI QUATRO QUEIJOS 1000G', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('MARC.PROPRIA RCR47', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('MARC.PROPRIA RFR51', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('RAVIOLI QUATRO QUEIJOS 250G', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('RAVIOLI DE FRANGO 1000G', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('RAVIOLI DE FRANGO ROMANHA 2KG', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('RAVIOLI DE CARNE ROMANHA 2KG', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('EXTRATO DE TOMATE 270GR', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('RETALHO DE CAPELETTI 500G', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('RETALHO CAPELETTI LEGUMES 500G', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('CAPELLETI DE CARNE', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('SORVETE NAPOLITANO', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('CAP. 5 QUEIJOS DE KILO', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('MARC.PROPRIA CCR46', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('MARC.PROPRIA CFR50', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('CAPELETTI DE LEGUMES 250G', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('CAPELETTI DE FRANGO 1000G', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('CAPELLETI DE CARNE ROMANHA 2KG', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('G', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('BISCOITO MARIA', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('BISCOITO MIGNON', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('BISCOITO AGUA E SAL', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('BISCOITO FOLHADO DOCE', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('FARINHA DE ROSCA', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('FARINHA DE ROSCA', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('FARINHA DE ROSCA', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('PRODUTO TESTE', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('FARINHA ROSCA', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('CANUDINHOS', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('QUEIJO RALADO', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('MASSA CASEIRA PAVIOLI', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('MACARRAO TIPO GRAVATA', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('BATATA PALHA', '10.99');
INSERT INTO Produto (Descricao, ValorUnitario) VALUES ('BATATA PALHA', '10.99');

INSERT INTO Pessoa VALUES ('Tousif', 'tousif@mail.com', 32);
INSERT INTO Pessoa VALUES ('Asif', 'asif@mail.com', 28);
INSERT INTO Pessoa VALUES ('Ramiz', 'ramiz@mail.com', 26);
INSERT INTO Pessoa VALUES ('Rizwan', 'rizwan@mail.com', 32);
INSERT INTO Pessoa VALUES ('Amol', 'amol@mail.com', 33);
INSERT INTO Pessoa VALUES ('Ramdas', 'ramdas@mail.com', 31);

INSERT INTO Cliente (Nome, Sexo, Idade) VALUES ('Fabinho', 'M', 23);
INSERT INTO Cliente (Nome, Sexo, Idade) VALUES ('Matheus', 'F', 21);
INSERT INTO Cliente (Nome, Sexo, Idade) VALUES ('Juca', 'M', 23);
INSERT INTO Cliente (Nome, Sexo, Idade) VALUES ('Andressa', 'F', 21);
INSERT INTO Cliente (Nome, Sexo, Idade) VALUES ('Júlia', 'F', 19);
INSERT INTO Cliente (Nome, Sexo, Idade) VALUES ('Eduarda', 'F', 20);

INSERT INTO Comanda (idCliente, Data, ValorTotal) VALUES (1, '2017-02-14 19:13:55', '23.50');
INSERT INTO Comanda (idCliente, Data, ValorTotal) VALUES (2, '2017-02-14 20:32:11', '28.90');
INSERT INTO Comanda (idCliente, Data, ValorTotal) VALUES (3, '2017-03-14 21:13:10', '32.00');
INSERT INTO Comanda (idCliente, Data, ValorTotal) VALUES (4, '2017-03-14 21:13:32', '30');
INSERT INTO Comanda (idCliente, Data, ValorTotal) VALUES (5, '2017-04-14 18:32:49', '0.00');
INSERT INTO Comanda (idCliente, Data, ValorTotal) VALUES (6, '2017-04-14 18:33:11', '0');

INSERT INTO Item_Comanda (idComanda, Item, Produto, Quantidade, ValorTotalItem) 
   VALUES (1, 1, 1, 2, '5.00'), (1, 2, 2, 1, '12.00'), (1, 3, 4, 1, '5.00');

INSERT INTO Item_Comanda (idComanda, Item, Produto, Quantidade, ValorTotalItem) 
   VALUES (2, 1, 1, 2, '2.40'), (2, 2, 2, 1, '8.99'), (2, 3, 4, 1, '52.00');